version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
    - 5432
    volumes:
      - ./deployments/pg:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432 
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=syncretism
    restart: unless-stopped
  service:
    depends_on:
      - postgres
      - lines-provider
    build:
      context: ./
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./:/app
    restart: always 
  lines-provider:
    image: antonboom/lines-provider
    container_name: lines-provider
    expose:
      - 8000
    ports:
      - 8000:8000